apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: demo-web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: web-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: demo-web
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes Simple Web</title>
      <style>
        body { background-color: #1e293b; color: white; text-align: center; padding-top: 10%; font-family: sans-serif; }
        h1 { color: #38bdf8; }
      </style>
    </head>
    <body>
      <h1> Welcome to My Kubernetes Web App</h1>
      <p>Running inside namespace <strong>demo-web</strong> on KIND cluster</p>
    </body>
    </html>
